// src/components/App.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useStore } from '~/store'

const store = useStore()

const qualities = [
  { value: 'auto', text: 'Auto' },
  { value: 144, text: '144' },
  { value: 240, text: '240' },
  { value: 360, text: '360' },
  { value: 480, text: '480' },
  { value: 720, text: '720p60' },
  { value: 1080, text: '1080p60 (HD)' },
  { value: 1440, text: '1440p60 (HD)' },
  { value: 2160, text: '2160p60 (4K)' },
  { value: 4320, text: '4320p60 (8K)' },
]

const quality = computed({
  get: () => store.state.settings.quality,
  set: (value) =>
    store.commit('settings/setQuality', {
      quality: value,
    }),
})
</script>

<template>
  <v-app>
    <v-main class="fill-height">
      <v-container fluid>
        <div class="d-flex">
          <div class="mr-3 text-no-wrap">Highest quality:</div>
          <select
            v-model="quality"
            style="-webkit-appearance: menulist; border-style: solid"
          >
            <option
              v-for="option of qualities"
              :key="option.value"
              :value="option.value"
              v-text="option.text"
            />
          </select>
        </div>
      </v-container>
    </v-main>
  </v-app>
</template>

<style lang="scss">
html {
  overflow-y: hidden;
}
</style>

// src/components/App.tsx
import { Box, CssBaseline, GlobalStyles, Typography } from '@mui/material'
import { ChangeEvent } from 'react'
import { StoreProvider } from '~/contexts/StoreContext'
import { Settings } from '~/models'
import { useAppDispatch, useAppSelector } from '~/store'
import { selectQuality, setQuality } from '~/store/settings'

const qualityOptions = [
  { value: 'auto', text: 'Auto' },
  { value: 144, text: '144' },
  { value: 240, text: '240' },
  { value: 360, text: '360' },
  { value: 480, text: '480' },
  { value: 720, text: '720p60' },
  { value: 1080, text: '1080p60 (HD)' },
  { value: 1440, text: '1440p60 (HD)' },
  { value: 2160, text: '2160p60 (4K)' },
  { value: 4320, text: '4320p60 (8K)' },
]

const InnerApp = () => {
  const quality = useAppSelector(selectQuality)
  const dispatch = useAppDispatch()

  const handleChangeQuality = (e: ChangeEvent<HTMLSelectElement>) => {
    const value = e.currentTarget.value as Settings['quality']
    dispatch(setQuality(value))
  }

  return (
    <Box sx={{ display: 'flex', mx: 2, my: 1 }}>
      <Typography sx={{ mr: 1 }} variant="subtitle2">
        Highest quality:
      </Typography>
      <select
        onChange={handleChangeQuality}
        style={{ WebkitAppearance: 'menulist', borderStyle: 'solid' }}
        value={quality}
      >
        {qualityOptions.map((option) => (
          <option key={option.value} value={option.value}>
            {option.text}
          </option>
        ))}
      </select>
    </Box>
  )
}

const App = () => {
  return (
    <StoreProvider>
      <CssBaseline />
      <GlobalStyles
        styles={{
          html: { overflowY: 'hidden', width: 250 },
        }}
      />
      <InnerApp />
    </StoreProvider>
  )
}

export default App
